In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.read_csv("raw_jobs_10k.csv")

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
0,JOB07402,Frontend Developer,DataBridge Analytics,"Gurgaon, India",We are looking for a Frontend Developer to joi...,1-3 years,B.E.,9-14 LPA,Full-time
1,JOB05835,Software Engineer,Vertex Digital,"Mumbai, India",We are looking for a Software Engineer to join...,3-5 years,Bachelor's Degree,12-16 LPA,Internship
2,JOB02123,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,1-3 years,B.E.,8-11 LPA,Full-time
3,JOB08789,Cloud Engineer,Apex Solutions,"Mumbai, India",We are looking for a Cloud Engineer to join ou...,3-5 years,Master's Degree,11-16 LPA,Full-time
4,JOB00305,Frontend Developer,Quantix Technologies,"Noida, India",We are looking for a Frontend Developer to joi...,3-5 years,B.Tech,10-12 LPA,Full-time
...,...,...,...,...,...,...,...,...,...
10095,JOB05735,Data Scientist,BlueOrbit Software,"Noida, India",We are looking for a Data Scientist to join ou...,3-5 years,B.Tech/M.Tech,7-10 LPA,Full-time
10096,JOB05192,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,0-2 years,Master's Degree,3-6 LPA,Internship
10097,JOB05391,Data Scientist,CodeCraft India,"Gwalior, India",We are looking for a Data Scientist to join ou...,2-4 years,B.Tech/M.Tech,7-12 LPA,Full-time
10098,JOB00861,Data Analyst,CloudSphere,Remote,We are looking for a Data Analyst to join our ...,2-4 years,B.Tech/M.Tech,5-7 LPA,Part-time
10099,JOB07271,Machine Learning Engineer,TechNova Solutions,"Noida, India",We are looking for a Machine Learning Engineer...,0-2 years,B.Tech,4-7 LPA,Full-time

#**EDA**

**Overview and Inspection Commands**

In [4]:
df=pd.read_csv("raw_jobs_10k.csv")

In [5]:
len(df)

10100

In [6]:
df.shape

(10100, 9)

In [7]:
df.dtypes

job_id             object
job_title          object
company            object
location           object
job_description    object
experience         object
education          object
salary             object
job_type           object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           10100 non-null  object
 1   job_title        10100 non-null  object
 2   company          10100 non-null  object
 3   location         10020 non-null  object
 4   job_description  10100 non-null  object
 5   experience       10100 non-null  object
 6   education        9979 non-null   object
 7   salary           9899 non-null   object
 8   job_type         10100 non-null  object
dtypes: object(9)
memory usage: 710.3+ KB

In [9]:
df.head()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
0,JOB07402,Frontend Developer,DataBridge Analytics,"Gurgaon, India",We are looking for a Frontend Developer to joi...,1-3 years,B.E.,9-14 LPA,Full-time
1,JOB05835,Software Engineer,Vertex Digital,"Mumbai, India",We are looking for a Software Engineer to join...,3-5 years,Bachelor's Degree,12-16 LPA,Internship
2,JOB02123,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,1-3 years,B.E.,8-11 LPA,Full-time
3,JOB08789,Cloud Engineer,Apex Solutions,"Mumbai, India",We are looking for a Cloud Engineer to join ou...,3-5 years,Master's Degree,11-16 LPA,Full-time
4,JOB00305,Frontend Developer,Quantix Technologies,"Noida, India",We are looking for a Frontend Developer to joi...,3-5 years,B.Tech,10-12 LPA,Full-time

In [10]:
df.tail()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
10095,JOB05735,Data Scientist,BlueOrbit Software,"Noida, India",We are looking for a Data Scientist to join ou...,3-5 years,B.Tech/M.Tech,7-10 LPA,Full-time
10096,JOB05192,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,0-2 years,Master's Degree,3-6 LPA,Internship
10097,JOB05391,Data Scientist,CodeCraft India,"Gwalior, India",We are looking for a Data Scientist to join ou...,2-4 years,B.Tech/M.Tech,7-12 LPA,Full-time
10098,JOB00861,Data Analyst,CloudSphere,Remote,We are looking for a Data Analyst to join our ...,2-4 years,B.Tech/M.Tech,5-7 LPA,Part-time
10099,JOB07271,Machine Learning Engineer,TechNova Solutions,"Noida, India",We are looking for a Machine Learning Engineer...,0-2 years,B.Tech,4-7 LPA,Full-time

In [11]:
df.sample(5)

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
670,JOB06881,Software Engineer,FinEdge Technologies,"Pune, India",We are looking for a Software Engineer to join...,5-8 years,Bachelor's Degree,10-13 LPA,Contract
4755,JOB00979,Cloud Engineer,NexaWorks,"Bangalore, India",We are looking for a Cloud Engineer to join ou...,2-4 years,B.E.,8-13 LPA,Full-time
6509,JOB03172,QA Engineer,Apex Solutions,"Gurgaon, India",We are looking for a QA Engineer to join our t...,5-8 years,B.Tech,9-11 LPA,Contract
126,JOB01531,Frontend Developer,CodeCraft India,"Hyderabad, India",We are looking for a Frontend Developer to joi...,5-8 years,B.E.,9-12 LPA,Contract
1495,JOB06171,Cloud Engineer,FinEdge Technologies,"Hyderabad, India",We are looking for a Cloud Engineer to join ou...,1-3 years,B.E.,10-14 LPA,Full-time

**Statistics and Counts**

In [12]:
df.describe()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
count,10100,10100,10100,10020,10100,10100,9979,9899,10100
unique,10000,10,12,10,8908,5,5,40,4
top,JOB01720,Cloud Engineer,CloudSphere,"Chennai, India",We are looking for a Business Analyst to join ...,2-4 years,Master's Degree,6-9 LPA,Full-time
freq,2,1044,884,1024,5,2055,2101,391,7094

In [13]:
df.nunique()

job_id             10000
job_title             10
company               12
location              10
job_description     8908
experience             5
education              5
salary                40
job_type               4
dtype: int64

In [14]:
df['job_title'].value_counts()

job_title
Cloud Engineer               1044
Business Analyst             1044
Backend Developer            1040
QA Engineer                  1038
Data Analyst                 1027
Software Engineer            1002
Machine Learning Engineer     991
Frontend Developer            978
DevOps Engineer               969
Data Scientist                967
Name: count, dtype: int64

**Missing values and Duplicates**

In [15]:
df.isnull().sum()

job_id               0
job_title            0
company              0
location            80
job_description      0
experience           0
education          121
salary             201
job_type             0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(100)

#**Data Cleaning**

**Conditional Filtering**

In [17]:
df[df['job_type'] == 'Full-Time']

Empty DataFrame
Columns: [job_id, job_title, company, location, job_description, experience, education, salary, job_type]
Index: []

In [18]:
df[df['job_type'].str.contains('full-Time', case=False, na=False)]

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
0,JOB07402,Frontend Developer,DataBridge Analytics,"Gurgaon, India",We are looking for a Frontend Developer to joi...,1-3 years,B.E.,9-14 LPA,Full-time
2,JOB02123,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,1-3 years,B.E.,8-11 LPA,Full-time
3,JOB08789,Cloud Engineer,Apex Solutions,"Mumbai, India",We are looking for a Cloud Engineer to join ou...,3-5 years,Master's Degree,11-16 LPA,Full-time
4,JOB00305,Frontend Developer,Quantix Technologies,"Noida, India",We are looking for a Frontend Developer to joi...,3-5 years,B.Tech,10-12 LPA,Full-time
5,JOB02532,Data Analyst,NexaWorks,"Bangalore, India",We are looking for a Data Analyst to join our ...,5-8 years,B.E.,5-10 LPA,Full-time
...,...,...,...,...,...,...,...,...,...
10092,JOB04427,Machine Learning Engineer,Quantix Technologies,"Bangalore, India",We are looking for a Machine Learning Engineer...,1-3 years,B.Tech,6-10 LPA,Full-time
10093,JOB00467,Frontend Developer,NexaWorks,Remote,We are looking for a Frontend Developer to joi...,5-8 years,B.E.,9-11 LPA,Full-time
10095,JOB05735,Data Scientist,BlueOrbit Software,"Noida, India",We are looking for a Data Scientist to join ou...,3-5 years,B.Tech/M.Tech,7-10 LPA,Full-time
10097,JOB05391,Data Scientist,CodeCraft India,"Gwalior, India",We are looking for a Data Scientist to join ou...,2-4 years,B.Tech/M.Tech,7-12 LPA,Full-time
10099,JOB07271,Machine Learning Engineer,TechNova Solutions,"Noida, India",We are looking for a Machine Learning Engineer...,0-2 years,B.Tech,4-7 LPA,Full-time

In [26]:
(df.isnull().sum() / len(df)) * 100

job_id                0.000000
job_title             0.000000
company               0.000000
location              0.792079
job_description       0.000000
experience            0.000000
education             1.198020
salary                1.990099
job_type              0.000000
description_length    0.000000
dtype: float64

In [27]:
df['job_description'].str.len

In [28]:
df["description_length"] = df["job_description"].str.len()

In [29]:
df["description_length"].describe()

count    10100.000000
mean       355.154356
std         10.307320
min        330.000000
25%        348.000000
50%        355.000000
75%        362.000000
max        378.000000
Name: description_length, dtype: float64

In [30]:
df["description_length"].describe()

count    10100.000000
mean       355.154356
std         10.307320
min        330.000000
25%        348.000000
50%        355.000000
75%        362.000000
max        378.000000
Name: description_length, dtype: float64

In [ ]:
df["job_title"].value_counts().head(10)