In [1]:
import pandas as pd
import re

In [3]:
df = pd.read_csv("raw_jobs_10k.csv")

In [4]:
df.head()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
0,JOB07402,Frontend Developer,DataBridge Analytics,"Gurgaon, India",We are looking for a Frontend Developer to joi...,1-3 years,B.E.,9-14 LPA,Full-time
1,JOB05835,Software Engineer,Vertex Digital,"Mumbai, India",We are looking for a Software Engineer to join...,3-5 years,Bachelor's Degree,12-16 LPA,Internship
2,JOB02123,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,1-3 years,B.E.,8-11 LPA,Full-time
3,JOB08789,Cloud Engineer,Apex Solutions,"Mumbai, India",We are looking for a Cloud Engineer to join ou...,3-5 years,Master's Degree,11-16 LPA,Full-time
4,JOB00305,Frontend Developer,Quantix Technologies,"Noida, India",We are looking for a Frontend Developer to joi...,3-5 years,B.Tech,10-12 LPA,Full-time

In [5]:
df["job_description"].head()

0    We are looking for a Frontend Developer to joi...
1    We are looking for a Software Engineer to join...
2    We are looking for a Machine Learning Engineer...
3    We are looking for a Cloud Engineer to join ou...
4    We are looking for a Frontend Developer to joi...
Name: job_description, dtype: object

In [6]:
def clean_text(text):
    
    # Convert to string
    text = str(text)
    
    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)
    
    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)
    
    # Remove email addresses
    text = re.sub(r"\S+@\S+", "", text)
    
    # Remove phone numbers
    text = re.sub(r"\b\d{10}\b", "", text)
    
    # Remove special characters
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)
    
    # Convert to lowercase
    text = text.lower()
    
    return text.strip()

In [7]:
df["clean_description"] = df["job_description"].apply(clean_text)

In [8]:
print("ORIGINAL:")
print(df["job_description"].iloc[0])

print("\nCLEANED:")
print(df["clean_description"].iloc[0])

ORIGINAL:
We are looking for a Frontend Developer to join our team. The candidate should have experience with Git, HTML, TypeScript, React, CSS and JavaScript. The role involves developing solutions, analyzing requirements, collaborating with cross-functional teams, and maintaining high-quality deliverables. Strong problem-solving and communication skills are preferred.

CLEANED:
we are looking for a frontend developer to join our team the candidate should have experience with git html typescript react css and javascript the role involves developing solutions analyzing requirements collaborating with cross functional teams and maintaining high quality deliverables strong problem solving and communication skills are preferred

In [9]:
df["clean_description"].isnull().sum()

np.int64(0)

In [10]:
empty = (df["clean_description"] == "").sum()

print("Empty descriptions:", empty)

Empty descriptions: 0

In [14]:
df["original_length"] = df["job_description"].str.len()

df["clean_length"] = df["clean_description"].str.len()

In [15]:
df[["original_length", "clean_length"]].head()

   original_length  clean_length
0              362           351
1              342           333
2              364           354
3              361           350
4              366           355

In [16]:
df[["original_length", "clean_length"]].head()

   original_length  clean_length
0              362           351
1              342           333
2              364           354
3              361           350
4              366           355